// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_K5NwFumwGLhHpxBQ6KvPWD1brByjlw4',
    appId: '1:885411879826:android:843e5323dca090946d7f4b',
    messagingSenderId: '885411879826',
    projectId: 'event-go-c36f9',
    storageBucket: 'event-go-c36f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGcWn3GcgVS6IAUYebYMZyKvSktpGSEsc',
    appId: '1:885411879826:ios:afafeae8f5578a5a6d7f4b',
    messagingSenderId: '885411879826',
    projectId: 'event-go-c36f9',
    storageBucket: 'event-go-c36f9.firebasestorage.app',
    androidClientId:
        '885411879826-d4sb88ahnig8t298h3oi4gqcpb380tdj.apps.googleusercontent.com',
    iosClientId:
        '885411879826-nngku4614gh1n66udplslgg90kg4qugn.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkInQr',
  );
}
